<?php
	/**
	 * @name: 404
	 * @package: views > admin
	 * @description: Template for the case of an unknown template request
	 * @author: Florian Götzrath <info@floriangoetzrath.de>
	 */
?>
<?php /* @var MainController $MC An instance of the MainController passed for use in this particular template */ ?>

<div id="admin-page">
	<div id="admin-page_inner" class="container">

		<header id="page-title">
			<div class="page-title_inner">
				<p class="page-title_pre">
					<?php echo HREFP_NAME; ?>
				</p>
				<h1 class="page-title_primary">
					Seite nicht gefunden
				</h1>
			</div>
		</header>

	</div>
</div>